# In order to execute, switch to this directory and run `docker compose up` from the command line
version: '3.1'

services:

  demo_mysql:
    container_name: demo_mysql
    restart: always
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass' # TODO: Change this
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - ./mysqldb:/var/lib/mysql
    ports:
      - "3306:3306"